def yamlInput
pipeline{
agent any
stages{
    stage('read yaml'){
        steps{
            script{
            yamlInput = readYaml file: "${WORKSPACE}/input.yaml"
            echo "Yamlfile: " + yamlInput
            echo yamlInput['app']['id'][0]
            }
    }
    }
    stage('test yaml'){
        steps{
            echo "YAML"
        }
    }
}
}
