def yamlInput
pipeline{
agent any
stages{
    stage('read yaml'){
        steps{
            script{
            yamlInput = readYaml file: "${WORKSPACE}/input.yaml"
            echo "Yamlfile: " + yamlInput
            echo yamlInput['app']['id'][0]
            }
    }
    }
    stage('Deployment'){
        stage{
            script{
                if (env.BRANCH_NAME == "master"){
                    print("This is prod Deployment")
                }
                else if (env.BRANCH_NAME == "develop"){
                    print("This is QA deployment")
                }
            }
        }
    }
}
}
